---
- hosts: all
  gather_facts: no
  tasks:
    - debug: var=env

- hosts: all
  become: no
  roles:
    - base

# - name: variable precedence test - common
#   hosts: common
#   tasks:
#     - include_vars: "vars/{{ env }}.yml"
#       when: env is defined
#     - debug: var=hdd_space_size

# - name: variable precedence test - localhost
#   hosts: localhost
#   tasks:
#     - include_vars: "vars/{{ env }}.yml"
#       when: env is defined
#     - include_vars: "vars/{{ function }}.yml"
#       when: function is defined
#     - debug: var=server_memory_size
#     - debug: var=env
#     - debug: var=hdd_space_size

# - name: variable precedence test - database
#   hosts: database
#   tasks:
#     - include_vars: "vars/{{ env }}.yml"
#       when: env is defined
#     - include_vars: "vars/{{ function }}.yml"
#       when: function is defined
#     - debug: var=server_memory_size
#     - debug: var=env
#     - debug: var=function
#     - debug: var=hdd_space_size

