- name: Create WORKSPACE directory
  file:
    group: 'staff'
    mode: '0755'
    owner: 'rcamara'
    path: '{{ tmp_exercise }}'
    state: directory

- tags: build
  block:
    - include_vars: vars/common.yml

    - include_vars: vars/build.yml
      when: env is defined

    - name: Create build.json
      template:
        src: common.json.j2
        dest: '{{ tmp_exercise }}/build.json'
        mode: '0770'

- tags: lab
  block:
    - include_vars: vars/common.yml

    - include_vars: vars/lab.yml
      when: env is defined

    - name: Create lab.json
      template:
        src: common.json.j2
        dest: '{{ tmp_exercise }}/lab.json'
        mode: '0770'