---
- hosts: all
  gather_facts: no
  tasks:
    - debug: var=env

- name: variable precedence test
  hosts: localhost
  tasks:
    - include_vars: "vars/{{ env }}.yml"
      when: env is defined
    - include_vars: "vars/{{ function }}.yml"
      when: function is defined
    - debug: var=server_memory_size
    - debug: var=env

- name: variable precedence test
  hosts: database
  tasks:
    - include_vars: "vars/{{ env }}.yml"
      when: env is defined
    - include_vars: "vars/{{ function }}.yml"
      when: function is defined
    - debug: var=server_memory_size
    - debug: var=env
    - debug: var=function

- name: variable precedence test
  hosts: common
  tasks:
    - include_vars: "vars/{{ env }}.yml"
      when: env is defined
    - debug: var=hdd_space_size